steps:
  # Step 1: Fetch password from Secret Manager and Login to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker login --username=$_DOCKER_USER --password-stdin <<< "$$DOCKER_PASSWORD"
    secretEnv: ['DOCKER_PASSWORD']
  # Step 2: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sla-dashboard-service'
      - '--image'
      - '$_DOCKER_USER/$_REPO_NAME:${_TAG}'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--project'
      - '$_PROJECT_ID'

substitutions:
  _DOCKER_USER: 'raghuporumamilla'
  _REPO_NAME: 'rporumamilla'
  _TAG: 'v1.0.0'
  _REGION: 'us-central1'
  _PROJECT_ID: event-hub-317019

availableSecrets:
  secretManager:
    - versionName: projects/$_PROJECT_ID/secrets/docker-hub-password/versions/latest
      env: 'DOCKER_PASSWORD'